logo:
  icon: '/images/avatar.webp'
  subtitle: 'Do the right thing | Blog by Hexo'

article:
  type: tech # tech/story
  auto_cover: true
  share: [wechat, email, link]

tag_plugins:
  # {% image %}
  image:
    fancybox: false



